# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/team_soc/minisys1_1/minisys1_1.srcs/sources/divu/divu.xci
# IP: The module: 'divu' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/team_soc/minisys1_1/minisys1_1.srcs/sources/divu/divu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divu'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/team_soc/minisys1_1/minisys1_1.srcs/sources/divu/divu.xci
# IP: The module: 'divu' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/team_soc/minisys1_1/minisys1_1.srcs/sources/divu/divu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divu'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
