# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/team_soc/minisys1_1/minisys1_1.srcs/sources/div/div.xci
# IP: The module: 'div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/team_soc/minisys1_1/minisys1_1.srcs/sources/div/div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/team_soc/minisys1_1/minisys1_1.srcs/sources/div/div.xci
# IP: The module: 'div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/team_soc/minisys1_1/minisys1_1.srcs/sources/div/div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
